namespace AutoSwitchInput
{
    [bindable]
    [default_interface]
    runtimeclass StyleResources 
    {
        StyleResources();

		static Microsoft.UI.Xaml.DependencyProperty ResourcesProperty { get; };

		static Microsoft.UI.Xaml.ResourceDictionary GetResources(Microsoft.UI.Xaml.DependencyObject obj);
		static void SetResources(Microsoft.UI.Xaml.DependencyObject obj, Microsoft.UI.Xaml.ResourceDictionary value);
    }
}
